version: 2
updates:
  # Maintenir les dépendances npm à jour
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      # Grouper les mises à jour mineures et de patch
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintenir les GitHub Actions à jour
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"